apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    REPLACE_WITH_BASE64_DOCKER_CONFIG

---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
type: Opaque
data:
  tracking_uri: REPLACE_BASE64_MLFLOW_URI

---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
type: Opaque
data:
  bootstrap_servers: REPLACE_BASE64_KAFKA_BOOTSTRAP

---
apiVersion: v1
kind: Secret
metadata:
  name: snowflake-secret
type: Opaque
data:
  account: REPLACE_BASE64_SNOWFLAKE_ACCOUNT
  user: REPLACE_BASE64_SNOWFLAKE_USER
  password: REPLACE_BASE64_SNOWFLAKE_PASSWORD
